# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/FBIGlowie/nix-index-database-stable/releases/download/2025-06-08-032454/index-";
  hashes = {
    x86_64-linux = "sha256-wYIGtRdwWxAI0p6YaXO93NP8ujDYOWp68X0G9nv9RXc=";
    aarch64-linux = "sha256-RGStKElB6StMmC9wrgU+SR4nZl5UXjsjr0SRmxb/9q4=";
    x86_64-darwin = "sha256-z76HLhjIXxwTK06o/vny0rcL+/E8hP7V7naKjQWRaz8=";
    aarch64-darwin = "sha256-tzF2MAsYOAV6CT+v39dOwhhElx8b4HSfO/OEX6PNuIk=";
  };
}
