# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/FBIGlowie/nix-index-database-stable/releases/download/2026-01-04-035212/index-";
  hashes = {
    x86_64-linux = "sha256-VGxYX0bWG6V+4If+w58mI6Pzbhb8Em/8ffviuXNOrNY=";
    aarch64-linux = "sha256-dimfiuTykxdSAoQ2lppmSHE+y/sf+t4CgNSHwM13G4Q=";
    x86_64-darwin = "sha256-I6miUQ7Y0fTv2GXQUxSNoziXabMuqUXOCR9TLVDpa0g=";
    aarch64-darwin = "sha256-Op9SyZIy/JyoagNVufU/BeG7mRFroU9CcJFbSjktLTs=";
  };
}
