# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/FBIGlowie/nix-index-database-stable/releases/download/2025-02-02-024708/index-";
  hashes = {
    x86_64-linux = "sha256-YTDklUfTYjcQUQ8X+vjBH50tAdH0b3Lnlc4pX0BGLzA=";
    aarch64-linux = "sha256-vU2Jc4Y/Yg9lc2yl1mNJrXWeneJKOCkexBim/sf2GlA=";
    x86_64-darwin = "sha256-wBj9KbiZbhqlJFPruz9+Gi+/GIPwb7tccXcF9D9kg3c=";
    aarch64-darwin = "sha256-6AIub6kG/Yox/V1Wnm8UA/yUocFsqp4dR5OLkjhDdM0=";
  };
}
